<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .special{
                color: #ffd700 ;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            .button {
                background-color: #719e40; /* Green */
                border: none;
                color: white;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                border-radius: 12px;
            } 
        </style>
    </head>
    <body>
        <h1>Eslim<a class="special"> Premium</a></h1>
        <div>An improved version of the microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Only $24 USD per trimester<!--<?= htmlspecialchars($name); ?>!--></h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
        <button type="button" class="button" onclick="window.location.href='https://www.youtube.com/watch?v=dQw4w9WgXcQ'">Buy Now!</button> 
    </body>
</html>
